In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.empty(5,4)
print(x)

tensor([[3.1027e-07, 4.5866e-41, 2.2561e-43, 0.0000e+00],
        [1.5186e-34, 4.5867e-41, 7.0252e-01, 3.1325e-41],
        [3.1027e-07, 4.5866e-41, 3.1028e-07, 4.5866e-41],
        [3.1028e-07, 4.5866e-41, 3.1028e-07, 4.5866e-41],
        [3.1028e-07, 4.5866e-41, 3.1028e-07, 4.5866e-41]])


In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2)

tensor([0., 0.])

In [ ]:
torch.rand(5,6)

tensor([[0.3997, 0.7457, 0.0073, 0.6702, 0.7802, 0.1476],
        [0.9624, 0.9832, 0.9804, 0.4998, 0.4396, 0.5280],
        [0.0756, 0.7510, 0.1395, 0.8442, 0.8172, 0.3141],
        [0.6124, 0.6561, 0.9746, 0.6877, 0.8340, 0.7823],
        [0.4609, 0.2943, 0.2471, 0.8599, 0.6863, 0.8361]])

In [ ]:
l = [13,4]
r = np.array([4,56,7])

In [ ]:
torch.tensor([l])

tensor([[13,  4]])

In [ ]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [ ]:
x.size() # like shape

torch.Size([5, 4])

In [ ]:
type(x)

torch.Tensor

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [ ]:
x + y

tensor([[1.5972, 1.1895],
        [1.5316, 0.4132]])

In [ ]:
torch.add(x,y)

tensor([[1.5972, 1.1895],
        [1.5316, 0.4132]])

In [ ]:
y.add(x)

tensor([[1.5972, 1.1895],
        [1.5316, 0.4132]])

In [ ]:
y

tensor([[0.8983, 0.2173],
        [0.5325, 0.0978]])

In [ ]:
y.add_(x) # '_'는 데이터 프레임에서 inplace같은 동작

tensor([[1.5972, 1.1895],
        [1.5316, 0.4132]])

In [ ]:
y[1,1]  # 1행 1열

tensor(0.4132)

In [ ]:
y[:,1] # 데이터 프레임 loc와 같다.

In [ ]:
x = torch.rand(8,8)
x

tensor([[0.8088, 0.4531, 0.7913, 0.7288, 0.8252, 0.1426, 0.8403, 0.1332],
        [0.7954, 0.0308, 0.7579, 0.2061, 0.5624, 0.1923, 0.6397, 0.3946],
        [0.4946, 0.5852, 0.1786, 0.7383, 0.7682, 0.5900, 0.9129, 0.6525],
        [0.2508, 0.0738, 0.5557, 0.0697, 0.6662, 0.1971, 0.1671, 0.4120],
        [0.1287, 0.6019, 0.8068, 0.4948, 0.8172, 0.5367, 0.7209, 0.1707],
        [0.2872, 0.6233, 0.3328, 0.9043, 0.5240, 0.4703, 0.6219, 0.9184],
        [0.8151, 0.2854, 0.1120, 0.3807, 0.5373, 0.1454, 0.5401, 0.4901],
        [0.3223, 0.9708, 0.6168, 0.2794, 0.0996, 0.5005, 0.1197, 0.0048]])

In [ ]:
x.view(64) # view는 사이즈를 자유롭게 바꿀 수 있다.
# 즉 x.view(64) 뜻은 64개 데이터를 잉렬로 나열하겠다 것이다.

tensor([0.8088, 0.4531, 0.7913, 0.7288, 0.8252, 0.1426, 0.8403, 0.1332, 0.7954,
        0.0308, 0.7579, 0.2061, 0.5624, 0.1923, 0.6397, 0.3946, 0.4946, 0.5852,
        0.1786, 0.7383, 0.7682, 0.5900, 0.9129, 0.6525, 0.2508, 0.0738, 0.5557,
        0.0697, 0.6662, 0.1971, 0.1671, 0.4120, 0.1287, 0.6019, 0.8068, 0.4948,
        0.8172, 0.5367, 0.7209, 0.1707, 0.2872, 0.6233, 0.3328, 0.9043, 0.5240,
        0.4703, 0.6219, 0.9184, 0.8151, 0.2854, 0.1120, 0.3807, 0.5373, 0.1454,
        0.5401, 0.4901, 0.3223, 0.9708, 0.6168, 0.2794, 0.0996, 0.5005, 0.1197,
        0.0048])

In [ ]:
x.view(4,16) # 4 x 16으로 바꾸기

tensor([[0.8088, 0.4531, 0.7913, 0.7288, 0.8252, 0.1426, 0.8403, 0.1332, 0.7954,
         0.0308, 0.7579, 0.2061, 0.5624, 0.1923, 0.6397, 0.3946],
        [0.4946, 0.5852, 0.1786, 0.7383, 0.7682, 0.5900, 0.9129, 0.6525, 0.2508,
         0.0738, 0.5557, 0.0697, 0.6662, 0.1971, 0.1671, 0.4120],
        [0.1287, 0.6019, 0.8068, 0.4948, 0.8172, 0.5367, 0.7209, 0.1707, 0.2872,
         0.6233, 0.3328, 0.9043, 0.5240, 0.4703, 0.6219, 0.9184],
        [0.8151, 0.2854, 0.1120, 0.3807, 0.5373, 0.1454, 0.5401, 0.4901, 0.3223,
         0.9708, 0.6168, 0.2794, 0.0996, 0.5005, 0.1197, 0.0048]])

In [ ]:
x.view(-1,16) # -1을 입력하면 16이 열이 생기고 행은 자동으로 계산해준다.
# -1은 자주 사용되는 표

tensor([[0.8088, 0.4531, 0.7913, 0.7288, 0.8252, 0.1426, 0.8403, 0.1332, 0.7954,
         0.0308, 0.7579, 0.2061, 0.5624, 0.1923, 0.6397, 0.3946],
        [0.4946, 0.5852, 0.1786, 0.7383, 0.7682, 0.5900, 0.9129, 0.6525, 0.2508,
         0.0738, 0.5557, 0.0697, 0.6662, 0.1971, 0.1671, 0.4120],
        [0.1287, 0.6019, 0.8068, 0.4948, 0.8172, 0.5367, 0.7209, 0.1707, 0.2872,
         0.6233, 0.3328, 0.9043, 0.5240, 0.4703, 0.6219, 0.9184],
        [0.8151, 0.2854, 0.1120, 0.3807, 0.5373, 0.1454, 0.5401, 0.4901, 0.3223,
         0.9708, 0.6168, 0.2794, 0.0996, 0.5005, 0.1197, 0.0048]])

In [ ]:
x.view(-1,4,4) # 'x'를 3차원으로 바꾸고 두 번째와 세 번째 차원은 4로 설정 첫 번째 차원을 알아서 조절

tensor([[[0.8088, 0.4531, 0.7913, 0.7288],
         [0.8252, 0.1426, 0.8403, 0.1332],
         [0.7954, 0.0308, 0.7579, 0.2061],
         [0.5624, 0.1923, 0.6397, 0.3946]],

        [[0.4946, 0.5852, 0.1786, 0.7383],
         [0.7682, 0.5900, 0.9129, 0.6525],
         [0.2508, 0.0738, 0.5557, 0.0697],
         [0.6662, 0.1971, 0.1671, 0.4120]],

        [[0.1287, 0.6019, 0.8068, 0.4948],
         [0.8172, 0.5367, 0.7209, 0.1707],
         [0.2872, 0.6233, 0.3328, 0.9043],
         [0.5240, 0.4703, 0.6219, 0.9184]],

        [[0.8151, 0.2854, 0.1120, 0.3807],
         [0.5373, 0.1454, 0.5401, 0.4901],
         [0.3223, 0.9708, 0.6168, 0.2794],
         [0.0996, 0.5005, 0.1197, 0.0048]]])

In [ ]:
# 넘파이로 바꾸기
y = x.numpy()
y
# y = x.numpy(y) 이거는 올바르지 않는 구문

array([[0.8087874 , 0.45306486, 0.7912577 , 0.72880036, 0.8251714 ,
        0.14263695, 0.8402554 , 0.13317561],
       [0.7953549 , 0.03081024, 0.75786704, 0.20611131, 0.5623673 ,
        0.19233114, 0.63966477, 0.39461952],
       [0.49460864, 0.5851526 , 0.17858404, 0.73825336, 0.7682374 ,
        0.58998823, 0.91293395, 0.6524959 ],
       [0.2507785 , 0.073807  , 0.5557464 , 0.06968302, 0.6662326 ,
        0.19712144, 0.1670953 , 0.4119947 ],
       [0.12870121, 0.60188687, 0.8067667 , 0.49484473, 0.817176  ,
        0.53668576, 0.72094506, 0.17073596],
       [0.2872088 , 0.6232834 , 0.33280075, 0.90425676, 0.52401465,
        0.47026926, 0.6219109 , 0.9183525 ],
       [0.81514955, 0.28538018, 0.1119889 , 0.3806777 , 0.53725326,
        0.14535826, 0.5400593 , 0.4900648 ],
       [0.32234442, 0.97075135, 0.61682194, 0.27939975, 0.09956944,
        0.5005489 , 0.11972976, 0.00481111]], dtype=float32)

In [ ]:
type(y)

numpy.ndarray

In [ ]:
x = torch.ones([1])
x

tensor([1.])

In [ ]:
x.item()
# tensor 안에 있는 값을 추출 -> 원소가 한 개일 때만 사용 가능이다.
# 예를 들어 선형 회귀 모델에서 최소제곱법에서 loss 값을 직접 뽑고 싶을 때 사용

1.0